### ISSUE TITLE
incorrect operator predudece 

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/OpenQASM.jl#4]
e.g the following

```julia
s = """OPENQASM 2.0;
gate test_gate2(theta, phi) qreg_2, qreg_3, qreg_1 {
  x qreg_1;
  z qreg_2;
  rx(-(sin(theta))+2.0) qreg_3;
  rx(sin(theta)+tan(phi)) qreg_3;
  ry(cos(phi)-ln(phi)) qreg_3;
  ry(cos(phi)*sqrt(phi)) qreg_3;
  CX qreg_1, qreg_3;
}
"""
target_qasm = OpenQASM.parse(s).prog[1]
```

```julia
julia> target_qasm.body[3].cargs[1]|>OpenQASM.print_qasm
-sin(theta)+2.0
```

the negative sign is outside of `sin(theta)+2.0` instead of `(-sin(theta)) + 2.0`

@thautwarm know how to fix this?

**Comment by HandyKurniawan** [comment]
Hi @Roger-luo,

I don't see any differences between `-( sin(theta) )+2.0` and `(-sin(theta)) + 2.0`. I think that the `( )` will do nothing because there is only a single value inside.  For example. `(a) + (b)` will only become `a + b`.

But maybe you could elaborate more about the bug?

**Comment by Roger-luo** [comment]
I don't quite remember what was the issue, maybe I thought the sign was `-(... + 2.0)` I'm gonna close this first.
